# Web Development Project Template
# For React, Vue, Angular, and other web technologies

project_type: "web-development"
description: "Modern web development projects using JavaScript/TypeScript frameworks"
technologies: ["JavaScript", "TypeScript", "React", "Vue", "Angular", "Node.js"]

patterns:
  source_files: "src/.*\\.(js|ts|jsx|tsx|vue|svelte)$"
  config_files: "package\\.json$|tsconfig\\.json$|webpack\\.config\\.(js|ts)$|\\.env.*$|vite\\.config\\.(js|ts)$"
  test_files: ".*\\.(test|spec)\\.(js|ts|jsx|tsx)$"
  style_files: ".*\\.(css|scss|sass|less|styl)$"
  build_files: "dist/.*|build/.*"
  package_files: "package\\.json$|package-lock\\.json$|yarn\\.lock$"

documentation_sections:
  - name: "Project Overview"
    auto_update: true
    template: "web-project-overview.md"
    description: "Project purpose, technology stack, and key features"
  - name: "Architecture Overview"
    auto_update: true
    sections: ["Frontend", "Backend", "Database", "State Management", "Routing"]
    description: "System architecture and component relationships"
  - name: "API Documentation"
    auto_update: true
    generator: "api-docs-generator"
    description: "REST/GraphQL endpoints and data contracts"
  - name: "Component Library"
    auto_update: true
    generator: "component-docs-generator"
    description: "Reusable UI components and their usage"
  - name: "Development Setup"
    auto_update: true
    description: "Environment setup, dependencies, and build process"
  - name: "Testing Strategy"
    auto_update: true
    description: "Unit, integration, and E2E testing approaches"
  - name: "Deployment Guide"
    auto_update: false
    description: "Production deployment and CI/CD pipeline"

mcp_integration:
  recommended_servers: ["context7", "magic", "puppeteer"]
  optional_servers: ["sequential"]
  web_specific_servers: ["browser-automation", "lighthouse"]

personas:
  primary: ["architect", "frontend", "backend"]
  secondary: ["security", "performance", "qa"]
  specialized: ["ux", "devops"]

auto_doc:
  update_mode: "moderate"
  validation_level: "semantic"
  backup_enabled: true
  auto_commit: false

framework_detection:
  react:
    patterns: ["react", "jsx", "tsx", "create-react-app"]
    specific_files: ["src/App.jsx", "src/App.tsx", "public/index.html"]
  vue:
    patterns: ["vue", "@vue", "vue-cli"]
    specific_files: ["src/App.vue", "vue.config.js"]
  angular:
    patterns: ["@angular", "angular-cli"]
    specific_files: ["angular.json", "src/app/app.component.ts"]
  node:
    patterns: ["express", "fastify", "koa", "nestjs"]
    specific_files: ["server.js", "app.js", "src/main.ts"]

performance_monitoring:
  metrics: ["bundle_size", "load_time", "lighthouse_score"]
  thresholds:
    bundle_size: "500KB"
    load_time: "2s"
    lighthouse_score: 90