superclaude_framework:
  version: 1.0.0
  template: backend-api
  initialized: '2025-07-13T16:00:46.848Z'
project:
  type: backend-api
  description: Backend API development with REST/GraphQL and database integration
  technologies:
    - Node.js
    - Python
    - Java
    - Go
    - C#
    - PHP
patterns:
  source_files: src/.*\.(js|ts|py|java|go|cs|php|rb)$|app/.*\.(js|ts|py|java|go|cs|php|rb)$
  config_files: >-
    package\.json$|requirements\.txt$|pom\.xml$|go\.mod$|\.env.*$|config\.(js|ts|py|java|yaml|yml|json)$
  test_files: >-
    .*\.(test|spec)\.(js|ts|py|java|go|cs|php)$|tests/.*\.(js|ts|py|java|go|cs|php)$
  migration_files: migrations/.*\.(js|ts|py|sql)$|db/.*\.(js|ts|py|sql)$
  api_files: routes/.*|controllers/.*|handlers/.*|endpoints/.*
  package_files: package\.json$|requirements\.txt$|pom\.xml$|go\.mod$|Cargo\.toml$
documentation_sections:
  - name: Project Overview
    auto_update: true
    template: api-project-overview.md
    description: Service purpose, technology stack, and architecture
  - name: API Documentation
    auto_update: true
    generator: api-docs-generator
    description: REST/GraphQL endpoints, request/response schemas
  - name: Architecture Overview
    auto_update: true
    sections:
      - Service Layer
      - Data Layer
      - Authentication
      - Middleware
    description: System architecture and service relationships
  - name: Database Schema
    auto_update: true
    generator: database-docs-generator
    description: Database models, relationships, and migrations
  - name: Development Setup
    auto_update: true
    description: Environment setup, dependencies, and configuration
  - name: Testing Strategy
    auto_update: true
    description: Unit, integration, and API testing approaches
  - name: Deployment Guide
    auto_update: true
    description: Production deployment, Docker, and CI/CD
  - name: Security Considerations
    auto_update: true
    description: Authentication, authorization, and security measures
mcp_integration:
  recommended_servers:
    - context7
    - sequential
    - magic
  optional_servers:
    - puppeteer
  api_specific_servers:
    - postman
    - swagger
    - database-docs
personas:
  primary:
    - architect
    - backend
    - database
  secondary:
    - security
    - performance
    - devops
  specialized:
    - api-designer
    - data-engineer
auto_doc:
  update_mode: moderate
  validation_level: semantic
  backup_enabled: true
  auto_commit: false
