#!/bin/bash

# SuperClaude Documentation Maintenance
# Generated by @superclaude/autodoc-framework

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

case "$1" in
    "update")
        echo "📝 Updating documentation..."
        node "$PROJECT_ROOT/.superclaude/auto-documentation.js"
        ;;
    "validate")
        echo "🔍 Validating documentation..."
        node "$PROJECT_ROOT/.superclaude/auto-documentation.js" --validate
        ;;
    "status")
        echo "📊 SuperClaude status:"
        if [ -f "$PROJECT_ROOT/.superclaude-last-update" ]; then
            echo "Last update: $(cat "$PROJECT_ROOT/.superclaude-last-update")"
        else
            echo "No update history found"
        fi
        ;;
    "backup")
        echo "💾 Creating documentation backup..."
        timestamp=$(date +%Y%m%d_%H%M%S)
        backup_dir="$PROJECT_ROOT/.superclaude-backups/$timestamp"
        mkdir -p "$backup_dir"
        cp CLAUDE.md "$backup_dir/" 2>/dev/null || echo "CLAUDE.md not found"
        echo "Backup created in: $backup_dir"
        ;;
    "help"|*)
        echo "SuperClaude Documentation Maintenance:"
        echo ""
        echo "  update     - Update documentation sections"
        echo "  validate   - Validate documentation structure"
        echo "  status     - Show framework status"
        echo "  backup     - Create manual backup"
        echo "  help       - Show this help"
        ;;
esac
